name: CI Pull Request

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.java }} Pull Request setup

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Code Style
        run: './gradlew spotlessCheck'

      - name: Build
        run: './gradlew classes'

      - name: Test
        if: matrix.java == '11'
        run: './gradlew test jacocoTestReport'
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY_1 }}

      - name: Test
        if: matrix.java == '17'
        run: './gradlew test jacocoTestReport'
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY_2 }}

      - name: Test Report
        if: matrix.java == '17'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/test-results/**/*.xml

      - name: SonarQube
        if: matrix.java == '17'
        run: './gradlew sonar --info'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
