name: CI Pull Request

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    name: Pull Request Java ${{ matrix.java }} action

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Code Style
        run: './gradlew spotlessCheck'

      - name: Build
        run: './gradlew classes'

      - name: Test
        run: './gradlew test jacocoTestReport'

      - name: SonarQube
        if: matrix.java == '17'
        run: './gradlew sonar --info'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
